import localFont from "next/font/local";
import { Inter, Roboto_Mono, Poppins } from 'next/font/google';
import {  } from 'next/font/google';
import "./globals.css";
import Navbar from "@/components/Navbar";


const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-mono',
});

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: "Next.js Crash Course",
  description: "Generated by learn with Sumit & Programming Hero",
};

export default function RootLayout({ children }) {

 

  return (
    <html
      lang='en'
      className={`${inter.variable} ${roboto_mono.variable} max-w-7xl mx-auto px-4 bg-blue-950`}
    >
      <body className={`font-sans`}>
      <Navbar/>

        <div className={`min-h-screen pt-8 bg-blue-950 ${inter.variable} `}>
          {children}
        </div>
        <footer className='h-20'></footer>
      </body>
    </html>
  );
}
